/**
 * Deploy Foreman + a mock USDC to Base Sepolia, fund every role with gas,
 * seed the plant treasury, and emit lib/deployment.ts for the UI and agent.
 *
 * Run: node scripts/deploy.mjs
 */
import fs from "node:fs";
import { createPublicClient, createWalletClient, http, parseEther, formatEther } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { baseSepolia, hardhat } from "viem/chains";

const env = Object.fromEntries(
  fs
    .readFileSync(".env", "utf8")
    .split(/\r?\n/)
    .filter((l) => l.includes("=") && !l.trimStart().startsWith("#"))
    .map((l) => {
      const i = l.indexOf("=");
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    }),
);

const need = (k) => {
  if (!env[k]) throw new Error(`${k} missing from .env — run: node scripts/keys.mjs`);
  return env[k];
};

const artifact = (name) =>
  JSON.parse(fs.readFileSync(`artifacts/contracts/${name}.sol/${name}.json`, "utf8"));

const USDC = (n) => BigInt(Math.round(n * 1e6));
const MONTHLY_CAP = USDC(2_000);
const AUTO_APPROVE_MAX = USDC(500);
const TREASURY = USDC(50_000);
const GAS_PER_ROLE = parseEther("0.002");

const LOCAL = process.env.CHAIN === "local";
const chain = LOCAL ? hardhat : baseSepolia;
const rpc = LOCAL ? "http://127.0.0.1:8545" : env.BASE_SEPOLIA_RPC || "https://sepolia.base.org";
const explorer = LOCAL ? "" : "https://sepolia.basescan.org";

const plant = privateKeyToAccount(need("DEPLOYER_KEY"));
const agentAddr = need("NEXT_PUBLIC_AGENT_ADDRESS");
const supplierA = need("NEXT_PUBLIC_SUPPLIER_A");
const supplierB = need("NEXT_PUBLIC_SUPPLIER_B");

const publicClient = createPublicClient({ chain, transport: http(rpc) });
const wallet = createWalletClient({ account: plant, chain, transport: http(rpc) });

const wait = (hash) => publicClient.waitForTransactionReceipt({ hash });

async function deploy(name, args) {
  const { abi, bytecode } = artifact(name);
  const hash = await wallet.deployContract({ abi, bytecode, args });
  const { contractAddress } = await wait(hash);
  console.log(`  ${name.padEnd(9)} ${contractAddress}`);
  return { address: contractAddress, abi };
}

let balance = await publicClient.getBalance({ address: plant.address });

if (LOCAL && balance < parseEther("1")) {
  // Hardhat's node ships 20 funded accounts; account #0's key is public and
  // well known. Top the plant up from it so the same .env works locally.
  const faucet = createWalletClient({
    account: privateKeyToAccount(
      "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
    ),
    chain,
    transport: http(rpc),
  });
  await wait(await faucet.sendTransaction({ to: plant.address, value: parseEther("10") }));
  balance = await publicClient.getBalance({ address: plant.address });
}

console.log(`chain   ${chain.name} (${chain.id})`);
console.log(`plant   ${plant.address}  ${formatEther(balance)} ETH`);
if (balance < parseEther("0.01")) {
  throw new Error(
    `Not enough Base Sepolia ETH. Fund ${plant.address} at https://www.alchemy.com/faucets/base-sepolia`,
  );
}

console.log("\ndeploying...");
const usdc = await deploy("MockUSDC", []);
const foreman = await deploy("Foreman", [usdc.address, agentAddr, MONTHLY_CAP, AUTO_APPROVE_MAX]);

console.log("\nseeding treasury...");
const call = (c, functionName, args) =>
  wallet.writeContract({ address: c.address, abi: c.abi, functionName, args }).then(wait);

await call(usdc, "mint", [plant.address, TREASURY]);
await call(usdc, "approve", [foreman.address, TREASURY]);
await call(foreman, "deposit", [TREASURY]);
console.log(`  deposited ${Number(TREASURY) / 1e6} USDC`);

console.log("\nvetting suppliers...");
for (const [label, addr] of [["Sundara / A", supplierA], ["Precision / B", supplierB]]) {
  await call(foreman, "setSupplier", [addr, true]);
  console.log(`  ${label.padEnd(14)} ${addr}`);
}

console.log("\nfunding roles with gas...");
for (const [label, to] of [["agent", agentAddr], ["supplierA", supplierA], ["supplierB", supplierB]]) {
  const have = await publicClient.getBalance({ address: to });
  if (have >= GAS_PER_ROLE) {
    console.log(`  ${label.padEnd(10)} already funded`);
    continue;
  }
  await wait(await wallet.sendTransaction({ to, value: GAS_PER_ROLE }));
  console.log(`  ${label.padEnd(10)} ${formatEther(GAS_PER_ROLE)} ETH`);
}

// --- emit a single generated module the UI and agent both import ---
const out = `// GENERATED by scripts/deploy.mjs — do not edit.
export const CHAIN_ID = ${chain.id};
export const EXPLORER = "${explorer}";
export const FOREMAN_ADDRESS = "${foreman.address}" as const;
export const USDC_ADDRESS = "${usdc.address}" as const;
export const FOREMAN_ABI = ${JSON.stringify(foreman.abi)} as const;
export const USDC_ABI = ${JSON.stringify(usdc.abi)} as const;
`;
fs.mkdirSync("lib", { recursive: true });
fs.writeFileSync("lib/deployment.ts", out);

let dotenv = fs.readFileSync(".env", "utf8");
for (const [k, v] of [
  ["NEXT_PUBLIC_FOREMAN_ADDRESS", foreman.address],
  ["NEXT_PUBLIC_USDC_ADDRESS", usdc.address],
]) {
  const re = new RegExp(`^${k}=.*$`, "m");
  dotenv = re.test(dotenv) ? dotenv.replace(re, `${k}=${v}`) : `${dotenv.trimEnd()}\n${k}=${v}\n`;
}
fs.writeFileSync(".env", dotenv);

console.log(`\ndone. ${explorer ? `${explorer}/address/${foreman.address}` : foreman.address}`);
