/**
 * Gather everything a submission form asks for into one folder.
 *
 *   node scripts/submission.mjs
 *
 * The files already exist — the videos under public/, the images under
 * public/brand/, the subtitles under docs/. They are scattered because that is
 * where each one is used from, which is right for the repo and wrong for
 * somebody dragging files into a browser at midnight.
 *
 * `submission/` is gitignored: copying 15 MB of video into the repo a second
 * time to save a few clicks is a bad trade. Re-run this whenever a video is
 * re-rendered.
 */
import fs from "node:fs";
import path from "node:path";

const OUT = "submission";

/** Named for the field they go in, not for where they came from. */
const FILES = [
  ["public/pitch.mp4", "pitch-video.mp4", "Pitch Video — 2m01s, 1920x1080, narrated, captions burned in"],
  ["public/demo.mp4", "demo-video.mp4", "Demo Video — 2m35s, narrated, captioned, annotated, the real app"],
  ["docs/pitch.srt", "pitch-subtitles.srt", "Subtitle track for the pitch"],
  ["docs/demo.srt", "demo-subtitles.srt", "Subtitle track for the demo"],
  ["public/brand/01-the-problem.png", "image-1-the-problem.png", "Image 1 — 1280x720"],
  ["public/brand/02-the-loop.png", "image-2-the-loop.png", "Image 2 — 1280x720"],
  ["public/brand/03-two-lanes.png", "image-3-two-lanes.png", "Image 3 — 1280x720"],
  ["public/brand/04-what-the-contract-refuses.png", "image-4-trust-model.png", "Image 4 — 1280x720"],
  ["public/brand/logo.svg", "logo.svg", "Wordmark"],
  ["public/brand/logo-mark.svg", "logo-mark.svg", "Square mark, for an avatar field"],
  ["docs/dashboard.png", "screenshot-control-room.png", "The product itself, if you would rather lead with it"],
  ["docs/hackquest-submission.md", "FORM-TEXT.md", "Every text field, ready to paste"],
];

fs.mkdirSync(OUT, { recursive: true });

const rows = [];
let missing = 0;

for (const [from, to, what] of FILES) {
  if (!fs.existsSync(from)) {
    /* Named rather than skipped silently: a missing video is the difference
       between a complete submission and one that looks complete. */
    console.error(`  MISSING  ${from} — ${what}`);
    missing++;
    continue;
  }
  fs.copyFileSync(from, path.join(OUT, to));
  const mb = fs.statSync(from).size / 1e6;
  rows.push([to, mb >= 1 ? `${mb.toFixed(1)} MB` : `${Math.round(mb * 1000)} KB`, what]);
  console.log(`  ${to.padEnd(30)} ${what}`);
}

const width = Math.max(...rows.map((r) => r[0].length));
fs.writeFileSync(
  path.join(OUT, "README.txt"),
  [
    "Foreman — files for the submission form.",
    "",
    "Generated by scripts/submission.mjs. Re-run it after re-rendering a video.",
    "The text for every field is in FORM-TEXT.md next to these.",
    "",
    ...rows.map(([f, size, what]) => `${f.padEnd(width)}  ${size.padStart(7)}  ${what}`),
    "",
    "Live: https://foreman-six-psi.vercel.app",
    "      https://foreman-six-psi.vercel.app/deck",
    "      https://foreman-six-psi.vercel.app/dashboard",
    "",
  ].join("\n"),
);

console.log(`\n${rows.length} file(s) in ${OUT}/`);
if (missing > 0) {
  console.error(`${missing} missing — the submission is not complete.`);
  process.exit(1);
}
